Integrate the changes between genesis 1.1.11 and 1.1.12

diff --git a/genesis/configure b/genesis/configure
--- a/genesis/configure
+++ b/genesis/configure
@@ -1045,7 +1045,7 @@ EOF
 
 fi
 
-for ac_hdr in fcntl.h sys/file.h sys/time.h unistd.h vfork.h ndbm.h db1/ndbm.h gdbm-ndbm.h
+for ac_hdr in fcntl.h sys/file.h sys/time.h unistd.h vfork.h
 do
 ac_safe=`echo "$ac_hdr" | tr './\055' '___'`
 echo $ac_n "  Checking for <$ac_hdr>""... $ac_c" 1>&6
@@ -1081,32 +1081,6 @@ else
 fi
 done
 
-if eval "test \"`echo '$ac_cv_header_ndbm_h'`\" = yes"; then
-    cat >> confdefs.h <<\EOF
-#define DBM_H_FILE <ndbm.h>
-EOF
-elif eval "test \"`echo '$ac_cv_header_db1_ndbm_h'`\" = yes"; then
-    echo "** working around odd placement of ndbm.h file"
-    cat >> confdefs.h <<\EOF
-#define DBM_H_FILE <db1/ndbm.h>
-EOF
-elif eval "test \"`echo '$ac_cv_header_gdbm_ndbm_h'`\" = yes"; then
-    echo "** working around odd placement of ndbm.h file"
-    cat >> confdefs.h <<\EOF
-#define DBM_H_FILE <gdbm-ndbm.h>
-EOF
-else
-  cat <<END
-
-** ERROR: unable to find any ndbm implementation.  This package is required.
-** ERROR: You can get gdbm (a free dbm package) from:
-** ERROR:
-** ERROR:       ftp://prep.ai.mit.edu/pub/gnu/
-** ERROR:
-** ERROR: Install it and make sure the final library is in your search path.
-END
-  exit
-fi
 
 #########################################################
 echo $ac_n "  Checking for sys_siglist declaration in signal.h or unistd.h""... $ac_c" 1>&6
@@ -1687,88 +1661,6 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
-#
-## check for a dbm library to use..
-## -lgdbm has priority over -lndbm
-#
-have_dbm=no
-echo $ac_n "  Checking for -lgdbm""... $ac_c" 1>&6
-if eval "test \"`echo '$''{'ac_cv_lib_gdbm'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  ac_save_LIBS="$LIBS"
-LIBS="-lgdbm $LIBS"
-cat > conftest.$ac_ext <<EOF
-#line 1793 "configure"
-#include "confdefs.h"
-
-int main() { return 0; }
-int t() {
-dbm_open()
-; return 0; }
-EOF
-if eval $ac_link; then
-  rm -rf conftest*
-  eval "ac_cv_lib_gdbm=yes"
-else
-  rm -rf conftest*
-  eval "ac_cv_lib_gdbm=no"
-fi
-rm -f conftest*
-LIBS="$ac_save_LIBS"
-
-fi
-
-if eval "test \"`echo '$ac_cv_lib_'gdbm`\" = yes"; then
-  echo "$ac_t""yes" 1>&6
-  LIBS="-lgdbm $LIBS"
-else 
-  echo "$ac_t""no" 1>&6
-
-  echo $ac_n "  Checking for -lndbm""... $ac_c" 1>&6
-  if eval "test \"`echo '$''{'ac_cv_lib_ndbm'+set}'`\" = set"; then
-    echo $ac_n "(cached) $ac_c" 1>&6
-  else
-    ac_save_LIBS="$LIBS"
-    LIBS="-lndbm $LIBS"
-    cat > conftest.$ac_ext <<EOF
-#line 1793 "configure"
-#include "confdefs.h"
-
-int main() { return 0; }
-int t() {
-dbm_open()
-; return 0; }
-EOF
-    if eval $ac_link; then
-      rm -rf conftest*
-      eval "ac_cv_lib_ndbm=yes"
-    else
-      rm -rf conftest*
-      eval "ac_cv_lib_ndbm=no"
-    fi
-    rm -f conftest*
-    LIBS="$ac_save_LIBS"
-
-    if eval "test \"`echo '$ac_cv_lib_'ndbm`\" = yes"; then
-      echo "$ac_t""yes" 1>&6
-      if [ $SYS = "hp-hpux" ]; then
-          cat <<END
-** WARNING: the ndbm library in HPUX has been known to be dysfunctional,
-** WARNING: it is suggested you get the gdbm library from:
-** WARNING:
-** WARNING:    ftp://prep.ai.mit.edu/pub/gnu/
-** WARNING:
-** WARNING: and use it instead (reconfigure)
-END
-      fi
-      LIBS="-lndbm $LIBS"
-    else
-      echo "$ac_t""no" 1>&6
-    fi
-  fi
-fi
-
 #####
 # strftime is in -lintl on SCO UNIX.
 echo $ac_n "  Checking for -lintl""... $ac_c" 1>&6
@@ -2273,6 +2165,155 @@ EOF
 else
   echo "$ac_t""no" 1>&6
 fi
+
+#########################################################
+## Find an implementation of the db libraries
+
+echo 1>&6
+echo "  Checking for how to get db support" 1>&6
+
+# preferred entries are at the end of the list
+for ac_hdr in gdbm-ndbm.h db1/ndbm.h ndbm.h db.h
+do
+ac_safe=`echo "$ac_hdr" | tr './\055' '___'`
+echo $ac_n "    Checking for <$ac_hdr>""... $ac_c" 1>&6
+if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1130 "configure"
+#include "confdefs.h"
+#include <$ac_hdr>
+EOF
+eval "$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+ac_err=`grep -v '^ *+' conftest.out`
+if test -z "$ac_err"; then
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=yes"
+else
+  echo "$ac_err" >&5
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=no"
+fi
+rm -f conftest*
+fi
+if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+    ac_tr_hdr=HAVE_`echo $ac_hdr | tr '[a-z]./\055' '[A-Z]___'`
+  cat >> confdefs.h <<EOF
+#define $ac_tr_hdr 1
+EOF
+  db_header_to_use=$ac_hdr
+ 
+else
+  echo "$ac_t""no" 1>&6
+fi
+done
+
+if test -z "$db_header_to_use"; then
+  echo "      Unable to figure out what header to include to get db support" 1>&6
+  exit 1
+else
+  echo "      Using... <$ac_hdr>" 1>&6
+  cat >> confdefs.h <<EOF
+#define DBM_H_FILE <$db_header_to_use>
+EOF
+fi
+
+echo $ac_n "    Checking to see if DB_DBM_HSEARCH needs to be defined... $ac_c" 1>&6
+if eval "test \"`echo '$''{'ac_cv_db_dbm_hsearch'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1094 "configure"
+#include <$db_header_to_use>
+datum test_var;
+int main() { return 0; }
+EOF
+  if eval $ac_compile; then
+    ac_cv_db_dbm_hsearch=no
+  else
+    cat > conftest.$ac_ext <<EOF
+#line 1094 "configure"
+#define DB_DBM_HSEARCH 1
+#include <$db_header_to_use>
+datum test_var;
+int main() { return 0; }
+EOF
+    if eval $ac_compile; then
+      ac_cv_db_dbm_hsearch=yes
+    else
+      ac_cv_db_dbm_hsearch=no
+    fi
+  fi
+  rm -f conftest*
+fi
+
+echo "$ac_t""$ac_cv_db_dbm_hsearch" 1>&6
+if test $ac_cv_db_dbm_hsearch = yes; then
+  cat >> confdefs.h <<\EOF
+#define DB_DBM_HSEARCH 1
+EOF
+fi
+
+## check for a dbm library to use..
+
+for ac_lib in gdbm gdbm_compat ndbm db; do
+  echo $ac_n "    Checking for -l$ac_lib""... $ac_c" 1>&6
+  if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib'+set}'`\" = set"; then
+    echo $ac_n "(cached) $ac_c" 1>&6
+  else
+    ac_save_LIBS="$LIBS"
+    LIBS="-l$ac_lib $LIBS"
+    cat > conftest.$ac_ext <<EOF
+#line 1793 "configure"
+#include "confdefs.h"
+#define DB_DBM_HSEARCH 1
+#include <$db_header_to_use>
+int main() { return 0; }
+int t() {
+dbm_open(NULL, NULL, NULL)
+; return 0; }
+EOF
+    if eval $ac_link; then
+      eval "ac_cv_lib_$ac_lib=yes"
+    else
+      eval "ac_cv_lib_$ac_lib=no"
+    fi
+    rm -f conftest*
+    LIBS="$ac_save_LIBS"
+  fi
+
+  if eval "test \"`echo '$ac_cv_lib_'$ac_lib`\" = yes"; then
+    echo "$ac_t""yes" 1>&6
+    db_lib_to_use=$ac_lib
+  else 
+    echo "$ac_t""no" 1>&6
+  fi
+done
+
+if test -z "$db_lib_to_use"; then
+  echo "      Unable to figure out what library to ling to get db support"
+  exit 1
+else
+  LIBS="-l$db_lib_to_use $LIBS"
+  echo "      Using... -l$db_lib_to_use" 1>&6
+fi
+
+if eval "test \"`echo '$ac_cv_lib_'ndbm`\" = yes"; then
+  if [ $SYS = "hp-hpux" ]; then
+    cat <<END
+** WARNING: the ndbm library in HPUX has been known to be dysfunctional,
+** WARNING: it is suggested you get the gdbm library from:
+** WARNING:
+** WARNING:    ftp://prep.ai.mit.edu/pub/gnu/
+** WARNING:
+** WARNING: and use it instead (reconfigure)
+END
+  fi
+fi
+
+echo 1>&6
 
 ######################################################################
 echo "- Genesis Configuration"
